services:
  postgres:
    image: postgres:latest
    container_name: "postgres-project-2.9"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: "redis-project-2.9"
  backend:
    image: backend-project:latest
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST: "postgres"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      REDIS_HOST: "redis"
    container_name: "backend-project-2.9"
    depends_on:
      - postgres
      - redis
  frontend:
    image: frontend-project:latest
    container_name: "frontend-project-2.9"
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    container_name: "nginx-project-2.9"
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
volumes:
  postgres:
  nginx:
