services:
  redis:
    image: redis:latest
    container_name: "redis-project-2.4"
  backend:
    image: backend-project:latest
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: "redis"
    container_name: "backend-project-2.4"
  frontend:
    image: frontend-project:latest
    ports:
      - "80:5000"
    container_name: "frontend-project-2.4"
