services:
  postgres:
    image: postgres:latest
    container_name: "postgres-project-2.7"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: "redis-project-2.7"
  backend:
    image: backend-project:latest
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST: "postgres"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      REDIS_HOST: "redis"
    container_name: "backend-project-2.7"
    depends_on:
      - postgres
      - redis
  frontend:
    image: frontend-project:latest
    ports:
      - "80:5000"
    container_name: "frontend-project-2.7"
    depends_on:
      - backend
volumes:
  postgres:
